version: "3"

services:
  app:
    image: alatair8/devops-for-programmers-project-74:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: ["npm", "run", "test"]
  test:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: ["npm", "test"]