FROM node:14.18.1-slim
RUN echo "deb http://security.debian.org/debian-security bullseye-security main contrib non-free" > /etc/apt/sources.list
RUN apt-get update

# Устанавливаем рабочую директорию
WORKDIR /app

  # Важно для кеширования слоев
COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm ci

COPY . .

EXPOSE 8080

CMD npm start
